version: 2
registries:
  npm-registry-npm-pkg-github-com-caiocampos:
    type: npm-registry
    url: https://npm.pkg.github.com/caiocampos
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_CAIOCAMPOS_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  reviewers:
  - caiocampos
  assignees:
  - caiocampos
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.30
    - 14.14.36
    - 14.14.39
    - 15.0.0
    - 15.0.1
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.10
    - 3.6.8
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1101.3
    - 0.1102.10
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: karma
    versions:
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
  - dependency-name: ng-packagr
    versions:
    - 11.1.2
    - 11.1.3
    - 11.1.4
    - 11.2.2
    - 11.2.4
  - dependency-name: typescript
    versions:
    - 4.0.6
  registries:
  - npm-registry-npm-pkg-github-com-caiocampos
