language: node_js
node_js:
  - "12"
dist: trusty
sudo: required

branches:
  only:
  - master

before_install:
  - echo -e "\n//npm.pkg.github.com/:_authToken=\${GITHUB_TOKEN}" > .npmrc

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --base-href /tabs/
  - cd dist/tabs
  - cp index.html 404.html
  - cd ../..

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/tabs
  on:
    branch: master
