language: node_js
node_js:
  - "15"
dist: bionic
sudo: required

before_script:
  - npm install -g @angular/cli@12

jobs:
  include:
    - stage: pages
      script:
        - npm run build-lib-prod
        - ng lint
        - ng build --configuration production --base-href /tabs/
        - cd dist/tabs
        - cp index.html 404.html
        - cd ../..
      deploy: &pages
        provider: pages
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: dist/tabs
        on:
          branch: master
    - stage: npm
      script:
        - npm run build-lib-prod
      before_deploy:
        - cd dist/caiocampos/tabs
      deploy: &npm
        provider: npm
        skip_cleanup: true
        api_key: $NPM_TOKEN
        email: "caio.campos1204@gmail.com"
        on:
          tags: true
